CREATE TABLE temperature_records (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    measured_at TIMESTAMPTZ NOT NULL,
    temperature NUMERIC NOT NULL
);

CREATE INDEX idx_temperature_records_measured_at
    ON temperature_records (measured_at)
    INCLUDE (temperature);
